services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    tty: true
    networks:
      - nginx
    volumes:
      - ./config:/etc/nginx
      - ./logs:/var/log/nginx
      - ./html:/usr/share/nginx/html
      - ./ssl:/etc/ssl

    ports:
      - 80:80
      - 443:443

networks:
    nginx:
      name: nginx
